/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.Pet;

/**
 *
 * @author Pedro
 */
public class FormCadastrarPet extends javax.swing.JFrame {

    /**
     * Creates new form FormCadastrarPet
     */
    public FormCadastrarPet() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNome = new javax.swing.JLabel();
        txtfieldNome = new javax.swing.JTextField();
        lblRaca = new javax.swing.JLabel();
        txtfieldRaca = new javax.swing.JTextField();
        lblDataNascimento = new javax.swing.JLabel();
        txtfieldHabilidades = new javax.swing.JTextField();
        lblEspecie = new javax.swing.JLabel();
        txtfieldDataNascimento = new javax.swing.JTextField();
        lblGenero = new javax.swing.JLabel();
        jcboxGenero = new javax.swing.JComboBox<>();
        lblHabilidades = new javax.swing.JLabel();
        txtfieldEspecie = new javax.swing.JTextField();
        lblSelecionarFoto = new javax.swing.JLabel();
        btnSelecionarFoto = new javax.swing.JButton();
        txtArquivoSelecionado = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnFinalizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNome.setText("Digite o Nome do Pet:");
        lblNome.setToolTipText("");
        lblNome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtfieldNome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblRaca.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRaca.setText("Digite a Raça do Pet:");
        lblRaca.setToolTipText("");
        lblRaca.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtfieldRaca.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblDataNascimento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDataNascimento.setText("Digite a Data de Nascimento do Pet");
        lblDataNascimento.setToolTipText("");
        lblDataNascimento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtfieldHabilidades.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblEspecie.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEspecie.setText("Digite a Espécie do Pet:");
        lblEspecie.setToolTipText("");
        lblEspecie.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtfieldDataNascimento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblGenero.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblGenero.setText("Informe o Gênero do Pet");
        lblGenero.setToolTipText("");
        lblGenero.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jcboxGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino" }));

        lblHabilidades.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHabilidades.setText("Informe as Habilidades do Pet (opcional)");
        lblHabilidades.setToolTipText("");
        lblHabilidades.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtfieldEspecie.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblSelecionarFoto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSelecionarFoto.setText("Selecione uma Foto do Seu Pet (.jpg, .png)");
        lblSelecionarFoto.setToolTipText("");
        lblSelecionarFoto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnSelecionarFoto.setText("SELECIONAR FOTO");
        btnSelecionarFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarFotoActionPerformed(evt);
            }
        });

        txtArquivoSelecionado.setText("Nome do Arquivo");

        btnCancelar.setBackground(new java.awt.Color(255, 51, 102));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnFinalizar.setBackground(new java.awt.Color(30, 74, 145));
        btnFinalizar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnFinalizar.setText("FINALIZAR");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtfieldNome, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtfieldRaca)
                    .addComponent(txtfieldHabilidades)
                    .addComponent(txtfieldDataNascimento)
                    .addComponent(txtfieldEspecie)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNome)
                            .addComponent(lblRaca)
                            .addComponent(lblEspecie)
                            .addComponent(lblDataNascimento)
                            .addComponent(lblGenero)
                            .addComponent(jcboxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHabilidades)
                            .addComponent(lblSelecionarFoto))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSelecionarFoto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtArquivoSelecionado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtfieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRaca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtfieldRaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEspecie)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtfieldEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDataNascimento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtfieldDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblGenero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcboxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblHabilidades)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtfieldHabilidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSelecionarFoto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSelecionarFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtArquivoSelecionado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelecionarFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarFotoActionPerformed
        selecionarFoto();
    }//GEN-LAST:event_btnSelecionarFotoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        cadastrarPet();
    }//GEN-LAST:event_btnFinalizarActionPerformed

    private void selecionarFoto() {
        JFileChooser fileChooser = new JFileChooser();
        File arquivo = null;
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("png", "jpg", "jpeg");
        fileChooser.setFileFilter(filtro);
        
        int resultado = fileChooser.showDialog(this, "Selecionar");
        if(resultado == JFileChooser.APPROVE_OPTION){
            arquivo = fileChooser.getSelectedFile();
            txtArquivoSelecionado.setText("Arquivo Selecionado: " + arquivo.getName());
        }
    }
    
    private void cadastrarPet(){
        // Recuper Dados do pet
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCadastrarPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCadastrarPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCadastrarPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCadastrarPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCadastrarPet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnSelecionarFoto;
    private javax.swing.JComboBox<String> jcboxGenero;
    private javax.swing.JLabel lblDataNascimento;
    private javax.swing.JLabel lblEspecie;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblHabilidades;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblRaca;
    private javax.swing.JLabel lblSelecionarFoto;
    private javax.swing.JLabel txtArquivoSelecionado;
    private javax.swing.JTextField txtfieldDataNascimento;
    private javax.swing.JTextField txtfieldEspecie;
    private javax.swing.JTextField txtfieldHabilidades;
    private javax.swing.JTextField txtfieldNome;
    private javax.swing.JTextField txtfieldRaca;
    // End of variables declaration//GEN-END:variables

   

}
