/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.PessoaBD;
import model.Pessoa;

/**
 *
 * @author LucasTheobaldo
 */
public class FormPagnaUser extends javax.swing.JFrame {

    /**
     * Creates new form FormPagnaUser
     */
   //Singleton
    private static FormPagnaUser gerFormPagnaUser;
    
    public FormPagnaUser() {
        initComponents();
        
        if(Pessoa.Gen().getCpf() != null){
                PanelPessoa.setVisible(true);
                PanelCanil.setVisible(false);
            }else{
                PanelCanil.setVisible(true);
                PanelPessoa.setVisible(false);
            }  
    }

    public static FormPagnaUser Gen(){
        if(gerFormPagnaUser == null){
            gerFormPagnaUser = new FormPagnaUser();
        }
        return gerFormPagnaUser;
    }
    //Singleton

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelCanil = new javax.swing.JPanel();
        btnCadastro = new javax.swing.JButton();
        btnCadastro1 = new javax.swing.JButton();
        PanelPessoa = new javax.swing.JPanel();
        btnCadastro2 = new javax.swing.JButton();
        btnCadastro3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });

        btnCadastro.setBackground(new java.awt.Color(255, 51, 102));
        btnCadastro.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnCadastro.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastro.setText("Sair");
        btnCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroActionPerformed(evt);
            }
        });

        btnCadastro1.setBackground(new java.awt.Color(30, 74, 145));
        btnCadastro1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnCadastro1.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastro1.setText("Cadastrar Pet");
        btnCadastro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastro1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelCanilLayout = new javax.swing.GroupLayout(PanelCanil);
        PanelCanil.setLayout(PanelCanilLayout);
        PanelCanilLayout.setHorizontalGroup(
            PanelCanilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCanilLayout.createSequentialGroup()
                .addGroup(PanelCanilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCanilLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnCadastro1))
                    .addGroup(PanelCanilLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(btnCadastro)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelCanilLayout.setVerticalGroup(
            PanelCanilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCanilLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(btnCadastro1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(btnCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );

        PanelPessoa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PanelPessoasFocusGained(evt);
            }
        });

        btnCadastro2.setBackground(new java.awt.Color(255, 51, 102));
        btnCadastro2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnCadastro2.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastro2.setText("Sair");
        btnCadastro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastro2ActionPerformed(evt);
            }
        });

        btnCadastro3.setBackground(new java.awt.Color(30, 74, 145));
        btnCadastro3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnCadastro3.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastro3.setText("Adotar Pet");
        btnCadastro3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastro3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelPessoaLayout = new javax.swing.GroupLayout(PanelPessoa);
        PanelPessoa.setLayout(PanelPessoaLayout);
        PanelPessoaLayout.setHorizontalGroup(
            PanelPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPessoaLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(btnCadastro2)
                .addContainerGap(108, Short.MAX_VALUE))
            .addGroup(PanelPessoaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCadastro3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelPessoaLayout.setVerticalGroup(
            PanelPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPessoaLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(btnCadastro3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(btnCadastro2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelCanil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(PanelPessoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(12, 12, 12)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelCanil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(PanelPessoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(12, 12, 12)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroActionPerformed
        Gen().dispose();     
    }//GEN-LAST:event_btnCadastroActionPerformed

    private void btnCadastro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastro1ActionPerformed
        FormCadastrarPet.Gen().setVisible(true);
    }//GEN-LAST:event_btnCadastro1ActionPerformed

    private void btnCadastro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastro2ActionPerformed
        Gen().dispose(); 
    }//GEN-LAST:event_btnCadastro2ActionPerformed

    private void btnCadastro3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastro3ActionPerformed
        FormExibirPets.Gen().setVisible(true);
    }//GEN-LAST:event_btnCadastro3ActionPerformed

    private void PanelPessoasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PanelPessoasFocusGained
        
        
        
    }//GEN-LAST:event_PanelPessoasFocusGained

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        if(PessoaBD.Gen().consultarPessoaCpfExiste(FormLogin.Gen().getUserID())){
                PanelPessoa.setVisible(true);
                PanelCanil.setVisible(false);
            }else{
                PanelCanil.setVisible(true);
                PanelPessoa.setVisible(false);
            }  
    }//GEN-LAST:event_formFocusGained

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPagnaUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPagnaUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPagnaUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPagnaUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPagnaUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelCanil;
    private javax.swing.JPanel PanelPessoa;
    private javax.swing.JButton btnCadastro;
    private javax.swing.JButton btnCadastro1;
    private javax.swing.JButton btnCadastro2;
    private javax.swing.JButton btnCadastro3;
    // End of variables declaration//GEN-END:variables
}
